# Generated by Django 3.2 on 2022-02-22 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=100)),
                ('first_language', models.CharField(max_length=100)),
                ('desired_language', models.CharField(max_length=100)),
                ('work_experience_category', models.CharField(max_length=100)),
                ('work_experience', models.CharField(max_length=100)),
                ('worker_image', models.ImageField(default='default.jpg', upload_to=users.models.path_time)),
                ('random_identifier', models.CharField(max_length=100)),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('nonpaid', 'nonpaid')], default='nonpaid', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=100)),
                ('first_language', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('nonpaid', 'nonpaid')], default='nonpaid', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
