# Generated by Django 3.2 on 2022-01-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='first_language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
    ]
