# Generated by Django 3.2.7 on 2021-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='first_language',
            field=models.CharField(default='French', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='location',
            field=models.CharField(default='England', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='nationality',
            field=models.CharField(default='French', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='desired_language',
            field=models.CharField(default='Chinese', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='first_language',
            field=models.CharField(default='French', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='nationality',
            field=models.CharField(default='English', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='work_experience',
            field=models.CharField(default='Cutting rock', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='work_experience_category',
            field=models.CharField(default='I cut rock', max_length=100),
            preserve_default=False,
        ),
    ]
