# Generated by Django 3.2 on 2022-02-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
