# Generated by Django 3.2.7 on 2021-09-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostofferings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='offering',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='first_language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='work_category',
            field=models.CharField(max_length=100),
        ),
    ]
