# Generated by Django 3.2.7 on 2021-09-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('hostofferings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='host',
        ),
        migrations.AddField(
            model_name='offering',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.host'),
        ),
    ]
