# Generated by Django 3.2.7 on 2021-09-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostofferings', '0002_auto_20210923_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offering',
            old_name='worker',
            new_name='host',
        ),
    ]
