# Generated by Django 3.2.7 on 2021-09-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('hostofferings', '0003_rename_worker_offering_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='offering_image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='host',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.host'),
            preserve_default=False,
        ),
    ]
