# Generated by Django 3.2.7 on 2021-09-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostofferings', '0003_alter_offering_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='email',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='first_language',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='location',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='name',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='nationality',
        ),
    ]
