# Generated by Django 3.2.7 on 2021-10-06 10:30

from django.db import migrations, models
import hostofferings.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostofferings', '0004_auto_20210928_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='random_identifier',
            field=models.CharField(default='random', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offering',
            name='offering_image',
            field=models.ImageField(default='default.jpg', upload_to=hostofferings.models.path_time),
        ),
    ]
