# Generated by Django 3.2 on 2022-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(default='default_id', max_length=100),
            preserve_default=False,
        ),
    ]
