# Generated by Django 3.2 on 2022-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=1000)),
                ('price_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SixMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=500)),
                ('price_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='TwoYear',
        ),
    ]
