# Generated by Django 3.2 on 2022-04-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220415_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SixMonth',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='OneYear',
        ),
        migrations.DeleteModel(
            name='TwoYear',
        ),
    ]
